@startuml
set namespaceSeparator ::

class "sApport::Views::Report::components::report_details_body.dart::ReportDetailsBody" {
  +_ReportDetailsBodyState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "sApport::Views::Report::components::report_details_body.dart::ReportDetailsBody"

class "sApport::Views::Report::components::report_details_body.dart::_ReportDetailsBodyState" {
  +ReportViewModel reportViewModel
  +AppRouterDelegate routerDelegate
  +void initState()
  +Widget build()
  +bool backButtonInterceptor()
  +void dispose()
}

"sApport::Views::Report::components::report_details_body.dart::_ReportDetailsBodyState" o-- "sApport::ViewModel::BaseUser::report_view_model.dart::ReportViewModel"
"sApport::Views::Report::components::report_details_body.dart::_ReportDetailsBodyState" o-- "sApport::Router::app_router_delegate.dart::AppRouterDelegate"
"flutter::src::widgets::framework.dart::State" <|-- "sApport::Views::Report::components::report_details_body.dart::_ReportDetailsBodyState"
"flutter::src::widgets::binding.dart::WidgetsBindingObserver" <|-- "sApport::Views::Report::components::report_details_body.dart::_ReportDetailsBodyState"

class "sApport::Views::Report::components::report_list_body.dart::ReportListBody" {
  +_ReportListBodyState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "sApport::Views::Report::components::report_list_body.dart::ReportListBody"

class "sApport::Views::Report::components::report_list_body.dart::_ReportListBodyState" {
  +ReportViewModel reportViewModel
  +AppRouterDelegate routerDelegate
  +void initState()
  +Widget build()
}

"sApport::Views::Report::components::report_list_body.dart::_ReportListBodyState" o-- "sApport::ViewModel::BaseUser::report_view_model.dart::ReportViewModel"
"sApport::Views::Report::components::report_list_body.dart::_ReportListBodyState" o-- "sApport::Router::app_router_delegate.dart::AppRouterDelegate"
"flutter::src::widgets::framework.dart::State" <|-- "sApport::Views::Report::components::report_list_body.dart::_ReportListBodyState"

class "sApport::Views::Report::components::create_report_body.dart::CreateReportBody" {
  +_CreateReportBodyState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "sApport::Views::Report::components::create_report_body.dart::CreateReportBody"

class "sApport::Views::Report::components::create_report_body.dart::_CreateReportBodyState" {
  +ReportViewModel reportViewModel
  +AppRouterDelegate routerDelegate
  +void initState()
  +Widget build()
}

"sApport::Views::Report::components::create_report_body.dart::_CreateReportBodyState" o-- "sApport::ViewModel::BaseUser::report_view_model.dart::ReportViewModel"
"sApport::Views::Report::components::create_report_body.dart::_CreateReportBodyState" o-- "sApport::Router::app_router_delegate.dart::AppRouterDelegate"
"flutter::src::widgets::framework.dart::State" <|-- "sApport::Views::Report::components::create_report_body.dart::_CreateReportBodyState"

class "sApport::Views::Report::components::form::report_form.dart::ReportForm" {
  +ReportViewModel reportViewModel
  +SelectFieldBloc<String, dynamic> reportCategory
  +TextFieldBloc<dynamic> reportText
  +void onSubmitting()
}

"sApport::Views::Report::components::form::report_form.dart::ReportForm" o-- "sApport::ViewModel::BaseUser::report_view_model.dart::ReportViewModel"
"sApport::Views::Report::components::form::report_form.dart::ReportForm" o-- "form_bloc::src::blocs::field::field_bloc.dart::SelectFieldBloc<String, dynamic>"
"sApport::Views::Report::components::form::report_form.dart::ReportForm" o-- "form_bloc::src::blocs::field::field_bloc.dart::TextFieldBloc<dynamic>"
"form_bloc::src::blocs::form::form_bloc.dart::FormBloc" <|-- "sApport::Views::Report::components::form::report_form.dart::ReportForm"

class "sApport::Views::Report::report_details_screen.dart::ReportDetailsScreen" {
  {static} +String route
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "sApport::Views::Report::report_details_screen.dart::ReportDetailsScreen"

class "sApport::Views::Report::reports_list_screen.dart::ReportsListScreen" {
  {static} +String route
  +State<ReportsListScreen> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "sApport::Views::Report::reports_list_screen.dart::ReportsListScreen"

class "sApport::Views::Report::reports_list_screen.dart::_ReportsListScreenState" {
  +ReportViewModel reportViewModel
  +void initState()
  +Widget build()
}

"sApport::Views::Report::reports_list_screen.dart::_ReportsListScreenState" o-- "sApport::ViewModel::BaseUser::report_view_model.dart::ReportViewModel"
"flutter::src::widgets::framework.dart::State" <|-- "sApport::Views::Report::reports_list_screen.dart::_ReportsListScreenState"

class "sApport::Views::Report::create_report_screen.dart::CreateReportScreen" {
  {static} +String route
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "sApport::Views::Report::create_report_screen.dart::CreateReportScreen"


@enduml