@startuml ViwesUML
package Views {
    package Chat {
        class "ChatListItem" {
            +ChatViewModel* chatViewModel
            +User* userItem
        }
        "ChatListItem" o-- "ChatViewModel"
        "ChatListItem" o-- "User"

        class "MessageListItem" {
            +ChatViewModel* chatViewModel
            +Message* messageItem
            +int* index
        }
        "MessageListItem" o-- "ChatViewModel"
        "MessageListItem" o-- "Message"

        class "ChatAcceptDenyInput" {
            +ChatViewModel* chatViewModel
        }
        "ChatAcceptDenyInput" o-- "ChatViewModel"

        class "ChatTextInput" {
            +ChatViewModel* chatViewModel
        }
        "ChatTextInput" o-- "ChatViewModel"

        class "ChatsListConstructor" {
            +void scrollListener()
        }
        "ChatsListConstructor" o-- "ChatViewModel"

        class "MessagesListConstructor" {
            +Message* messageItem
            +void scrollListener()
        }
        "MessagesListConstructor" o-- "ChatViewModel"
        "MessagesListConstructor" o-- "Message"

        package BaseUser {
            package AnonymousChat::ActiveChatsList {
                class "ActiveChatsListScreen" {
                    +ChatViewModel* chatViewModel
                    +BaseUser* createUserCallback()
                    +void initChats()
                }
                "ActiveChatsListScreen" o-- "ChatViewModel"
            }

            package AnonymousChat::PendingChatsList {
                class "PendingChatsListScreen" {
                    +ChatViewModel* chatViewModel
                    +BaseUser* createUserCallback()
                    +void initChats()
                }
                "PendingChatsListScreen" o-- "ChatViewModel"
            }

            package ChatWithExperts {
                class "ChatWithExpertChatsListScreen" {
                    +ChatViewModel* chatViewModel
                    +Expert* createUserCallback()
                    +void initChats()
                }
                "ChatWithExpertChatsListScreen" o-- "ChatViewModel"
            }
        }

        package ChatPage {
            class "ChatPageScreen" {
                +ChatViewModel* chatViewModel
            }
            "ChatPageScreen" o-- "ChatViewModel"
        }

        package Expert {
        }
    }

    package Home {
        class "DashCard" {
            +String* imagePath
            +String* text
            +Function* press
        }

        class "Header" {
            +AuthViewModel* authViewModel
            +UserViewModel* userViewModel
            -dynamic _onAccountPressed()
        }
        "Header" o-- "AuthViewModel"
        "Header" o-- "UserViewModel"

        package BaseUser {
            class "BaseUserHomeScreen" {
                +AuthViewModel* authViewModel
                +BaseUserViewModel* baseUserViewModel
            }
            "BaseUserHomeScreen" o-- "AuthViewModel"
            "BaseUserHomeScreen" o-- "BaseUserViewModel"

            class "BaseUserGrid" {
                +BaseUserViewModel* baseUserViewModel
                +ChatViewModel* chatViewModel
            }
            "BaseUserGrid" o-- "BaseUserViewModel"
            "BaseUserGrid" o-- "ChatViewModel"

        }
        package Expert {
            class "ExpertHomeScreen" {
                +AuthViewModel* authViewModel
                +ExpertViewModel* expertViewModel
            }
            "ExpertHomeScreen" o-- "AuthViewModel"
            "ExpertHomeScreen" o-- "ExpertViewModel"

            class "ExpertGrid" {
                +ExpertViewModel* expertViewModel
                +ChatViewModel* chatViewModel
            }
            "ExpertGrid" o-- "ExpertViewModel"
            "ExpertGrid" o-- "ChatViewModel"
        }
    }

    package Login {
        class "LoginScreen" {
            +AuthViewModel* authViewModel
            +void navigateToHome()
        }
        "LoginScreen" o-- "AuthViewModel"
    }

    package Map {
        class "MapScreen" {
            +MapViewModel* mapViewModel
            +ChatViewModel* chatViewModel
            +GoogleMapController* controller
            -Future<void>* _goToPlace()
        }
        "MapScreen" o-- "MapViewModel"
        "MapScreen" o-- "ChatViewModel"
        "MapScreen" o-- "google_maps_flutter::GoogleMapController"
    }

    package Report {
        class "CreateReportScreen" {
            +BaseUserViewModel* baseUserViewModel
            +ReportViewModel* reportViewModel
            -dynamic _onReportSubmitted()
            -dynamic _onReportError()
        }
        "CreateReportScreen" o-- "BaseUserViewModel"
        "CreateReportScreen" o-- "ReportViewModel"

        class "ReportListScreen" {
            +ReportViewModel* reportViewModel
            +Widget* buildItem()
            +void scrollListener()
            -dynamic _onReportPressed()
        }
        "ReportListScreen" o-- "ReportViewModel"
    }

    package Signup {
        class "CredentialScreen" {
            +AuthViewModel* authViewModel
            +BaseUserInfoViewModel* infoViewModel
            +UserViewModel* userViewModel
            +User* user
            +void showSnackBar()
        }
        "CredentialScreen" o-- "AuthViewModel"
        "CredentialScreen" o-- "BaseUserInfoViewModel"
        "CredentialScreen" o-- "UserViewModel"
        "CredentialScreen" o-- "User"

        package BaseUser {
            class "BaseUserSignUpScreen" {
                +AuthViewModel* authViewModel
                +BaseUserInfoViewModel* baseUserInfoViewModel
                -dynamic _onAddressError()
                -dynamic _addressConfirmation()
            }
            "BaseUserSignUpScreen" o-- "AuthViewModel"
            "BaseUserSignUpScreen" o-- "ExpertInfoViewModel"
        }

        package Expert {
            class "ExpertsSignUpScreen" {
                +AuthViewModel* authViewModel
                +ExpertInfoViewModel* expertInfoViewModel
                -dynamic _onAddressError()
                -dynamic _addressConfirmation()
            }
            "ExpertsSignUpScreen" o-- "AuthViewModel"
            "ExpertsSignUpScreen" o-- "ExpertInfoViewModel"
        }
    }

    package Welcome {
        class "WelcomeScreen" {
            +AuthViewModel* authViewModel
            +BaseUserViewModel* baseUserViewModel
            +void navigateToHome()
        }
        "WelcomeScreen" o-- "AuthViewModel"
        "WelcomeScreen" o-- "BaseUserViewModel"
    }
}
@enduml